PACKAGE_NAME="vl_driver"
PACKAGE_VERSION="1.8.4"
MAKE[0]="bash dkms-build.sh ${kernelver} EPM-31"
CLEAN="true"
AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="vldrive"
BUILT_MODULE_LOCATION[0]="src/vldrive"
DEST_MODULE_LOCATION[0]="/updates/dkms"

BUILT_MODULE_NAME[1]="vldriveax"
BUILT_MODULE_LOCATION[1]="src/vldriveax"
DEST_MODULE_LOCATION[1]="/updates/dkms"

BUILT_MODULE_NAME[2]="vldrivep"
BUILT_MODULE_LOCATION[2]="src/vldrivep"
DEST_MODULE_LOCATION[2]="/updates/dkms"
