include_directories(
  BME68x_SensorAPI
)

set(GB_BME68x_CLASSES
  ${CMAKE_CURRENT_SOURCE_DIR}/../BME68x_SensorAPI/bme68x.c
)

add_library(${BME_LIB} SHARED
  ${GB_BME68x_CLASSES}
)

install(TARGETS ${BME_LIB} LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/lib)

if(INSTALL_HEADERS)
  install(DIRECTORY include/
    DESTINATION ${CMAKE_INSTALL_PREFIX}/include/GRAMSBalloon
    FILES_MATCHING PATTERN "*.h")
endif(INSTALL_HEADERS)
